using System.Text.Json.Serialization;

namespace GrznarAi.Trading.ReadOnly.Models.UserInfo;

public record UserSearchResponse(
    [property: JsonPropertyName("totalItems")] int TotalItems,
    [property: JsonPropertyName("items")] IReadOnlyList<UserSearchItem> Items
);

public record UserSearchItem(
    [property: JsonPropertyName("customerId")] int CustomerId,
    [property: JsonPropertyName("userName")] string? UserName,
    [property: JsonPropertyName("fullName")] string? FullName,
    [property: JsonPropertyName("hasAvatar")] bool HasAvatar,
    [property: JsonPropertyName("isSocialConnected")] bool IsSocialConnected,
    [property: JsonPropertyName("isTestAccount")] bool IsTestAccount,
    [property: JsonPropertyName("displayFullName")] bool DisplayFullName,
    [property: JsonPropertyName("bonusOnly")] bool BonusOnly,
    [property: JsonPropertyName("blocked")] bool Blocked,
    [property: JsonPropertyName("verified")] bool Verified,
    [property: JsonPropertyName("popularInvestor")] bool PopularInvestor,
    [property: JsonPropertyName("copyBlock")] bool CopyBlock,
    [property: JsonPropertyName("isFund")] bool IsFund,
    [property: JsonPropertyName("isBronze")] bool IsBronze,
    [property: JsonPropertyName("fundType")] int? FundType,
    [property: JsonPropertyName("tags")] IReadOnlyList<int>? Tags,
    [property: JsonPropertyName("gain")] decimal Gain,
    [property: JsonPropertyName("dailyGain")] decimal DailyGain,
    [property: JsonPropertyName("thisWeekGain")] decimal ThisWeekGain,
    [property: JsonPropertyName("riskScore")] int RiskScore,
    [property: JsonPropertyName("maxDailyRiskScore")] int MaxDailyRiskScore,
    [property: JsonPropertyName("maxMonthlyRiskScore")] int MaxMonthlyRiskScore,
    [property: JsonPropertyName("copiers")] int Copiers,
    [property: JsonPropertyName("copiedTrades")] int CopiedTrades,
    [property: JsonPropertyName("copyTradesPct")] decimal CopyTradesPct,
    [property: JsonPropertyName("copyInvestmentPct")] decimal CopyInvestmentPct,
    [property: JsonPropertyName("baseLineCopiers")] int BaseLineCopiers,
    [property: JsonPropertyName("copiersGain")] decimal CopiersGain,
    [property: JsonPropertyName("aumTier")] int AumTier,
    [property: JsonPropertyName("aumTierV2")] int AumTierV2,
    [property: JsonPropertyName("aumTierDesc")] string? AumTierDesc,
    [property: JsonPropertyName("virtualCopiers")] int VirtualCopiers,
    [property: JsonPropertyName("trades")] int Trades,
    [property: JsonPropertyName("winRatio")] decimal WinRatio,
    [property: JsonPropertyName("dailyDd")] decimal DailyDrawdown,
    [property: JsonPropertyName("weeklyDd")] decimal WeeklyDrawdown,
    [property: JsonPropertyName("profitableWeeksPct")] decimal ProfitableWeeksPct,
    [property: JsonPropertyName("profitableMonthsPct")] decimal ProfitableMonthsPct,
    [property: JsonPropertyName("velocity")] decimal Velocity,
    [property: JsonPropertyName("exposure")] decimal Exposure,
    [property: JsonPropertyName("avgPosSize")] decimal AveragePositionSize,
    [property: JsonPropertyName("optimalCopyPosSize")] decimal OptimalCopyPositionSize,
    [property: JsonPropertyName("highLeveragePct")] decimal HighLeveragePct,
    [property: JsonPropertyName("mediumLeveragePct")] decimal MediumLeveragePct,
    [property: JsonPropertyName("lowLeveragePct")] decimal LowLeveragePct,
    [property: JsonPropertyName("peakToValley")] decimal PeakToValley,
    [property: JsonPropertyName("peakToValleyStart")] DateTimeOffset? PeakToValleyStart,
    [property: JsonPropertyName("peakToValleyEnd")] DateTimeOffset? PeakToValleyEnd,
    [property: JsonPropertyName("longPosPct")] decimal LongPositionPct,
    [property: JsonPropertyName("topTradedInstrumentId")] int TopTradedInstrumentId,
    [property: JsonPropertyName("topTradedAssetClassId")] int TopTradedAssetClassId,
    [property: JsonPropertyName("topTradedInstrumentPct")] decimal TopTradedInstrumentPct,
    [property: JsonPropertyName("totalTradedInstruments")] int TotalTradedInstruments,
    [property: JsonPropertyName("activeWeeks")] int ActiveWeeks,
    [property: JsonPropertyName("firstActivity")] int FirstActivity,
    [property: JsonPropertyName("lastActivity")] int LastActivity,
    [property: JsonPropertyName("activeWeeksPct")] decimal ActiveWeeksPct,
    [property: JsonPropertyName("weeksSinceRegistration")] int WeeksSinceRegistration,
    [property: JsonPropertyName("country")] string? Country,
    [property: JsonPropertyName("affiliateId")] int AffiliateId,
    [property: JsonPropertyName("instrumentPct")] decimal InstrumentPct,
    [property: JsonPropertyName("countryId")] int CountryId,
    [property: JsonPropertyName("isPopularInvestor")] bool IsPopularInvestor,
    [property: JsonPropertyName("topTradedAssetId")] int TopTradedAssetId
);
