using System.Text.Json.Serialization;

namespace GrznarAi.Trading.ReadOnly.Etoro.Models.UserInfo;

public record UserTradeInfoResponse(
    [property: JsonPropertyName("userName")] string? UserName,
    [property: JsonPropertyName("fullName")] string? FullName,
    [property: JsonPropertyName("weeksSinceRegistration")] int WeeksSinceRegistration,
    [property: JsonPropertyName("countryId")] int CountryId,
    [property: JsonPropertyName("affiliateId")] int AffiliateId,
    [property: JsonPropertyName("isPopularInvestor")] bool IsPopularInvestor,
    [property: JsonPropertyName("isFund")] bool IsFund,
    [property: JsonPropertyName("hasAvatar")] bool HasAvatar,
    [property: JsonPropertyName("gain")] decimal Gain,
    [property: JsonPropertyName("dailyGain")] decimal DailyGain,
    [property: JsonPropertyName("thisWeekGain")] decimal ThisWeekGain,
    [property: JsonPropertyName("riskScore")] int RiskScore,
    [property: JsonPropertyName("maxDailyRiskScore")] int MaxDailyRiskScore,
    [property: JsonPropertyName("maxMonthlyRiskScore")] int MaxMonthlyRiskScore,
    [property: JsonPropertyName("copiers")] int Copiers,
    [property: JsonPropertyName("copiedTrades")] int CopiedTrades,
    [property: JsonPropertyName("copyTradesPct")] decimal CopyTradesPct,
    [property: JsonPropertyName("copyInvestmentPct")] decimal CopyInvestmentPct,
    [property: JsonPropertyName("baseLineCopiers")] int BaseLineCopiers,
    [property: JsonPropertyName("copiersGain")] decimal CopiersGain,
    [property: JsonPropertyName("aumTier")] int AumTier,
    [property: JsonPropertyName("aumTierDesc")] string? AumTierDesc,
    [property: JsonPropertyName("fundType")] int? FundType,
    [property: JsonPropertyName("virtualCopiers")] int VirtualCopiers,
    [property: JsonPropertyName("trades")] int Trades,
    [property: JsonPropertyName("topTradedInstrumentId")] int TopTradedInstrumentId,
    [property: JsonPropertyName("topTradedAssetId")] int TopTradedAssetId,
    [property: JsonPropertyName("winRatio")] decimal WinRatio,
    [property: JsonPropertyName("dailyDd")] decimal DailyDrawdown,
    [property: JsonPropertyName("weeklyDd")] decimal WeeklyDrawdown,
    [property: JsonPropertyName("peakToValley")] decimal PeakToValley,
    [property: JsonPropertyName("profitableWeeksPct")] decimal ProfitableWeeksPct,
    [property: JsonPropertyName("profitableMonthsPct")] decimal ProfitableMonthsPct,
    [property: JsonPropertyName("avgPosSize")] decimal AveragePositionSize,
    [property: JsonPropertyName("highLeveragePct")] decimal HighLeveragePct,
    [property: JsonPropertyName("mediumLeveragePct")] decimal MediumLeveragePct,
    [property: JsonPropertyName("lowLeveragePct")] decimal LowLeveragePct,
    [property: JsonPropertyName("firstActivity")] int FirstActivity,
    [property: JsonPropertyName("lastActivity")] int LastActivity,
    [property: JsonPropertyName("activeWeeksPct")] decimal ActiveWeeksPct,
    [property: JsonPropertyName("instrumentPct")] decimal InstrumentPct
);
